version: 0.1
 
phases:
    install:
        commands:
            - npm install
            - npm install -g @angular/cli
            
    build:
        commands:
            # - npm run-script build
             - ng build --prod 
            
   