import { NgbDateStruct } from "@ng-bootstrap/ng-bootstrap";

export class LeaseSearchCriteria {
/*
  public PropertyType: string;
  public ListingType: string;
  public MetroId: number;
  public CountryId: number;
  public CouncilId: number;
  public SubMarketId: number;
  public CityId: string;
  public NeighbourhoodId: number;
  public ZipCode: string;
  public SpecificUseId: string;
  // public SalePriceMin: number;
  // public SalePriceMax: number;
  public AskingRateMin: number;
  public AskingRateMax: number;
  // public SoldSFMin: number;
  // public SoldSFMax: number;
  public PolygonText: string;
  public CentreLatitude: number;
  public CentreLongitude: number;
  public CircleRadius: number;
  public StartingIndex: number;
  public OffsetValue: number;
  public SortParam: string;
  public SortDirection: string;
  //public IsMapSearch: boolean;
  public LatlngArray: any;
  // public Contacts: string;
  // public SaleDateMin: string;
  // public SaleDateMax: string;
  // public SaleDateMinFormat: NgbDateStruct;
  // public SaleDateMaxFormat: NgbDateStruct;
  // public PercentageOccupiedMin: string;
  // public PercentageOccupiedMax: string;
  public citySearchText: string;
  public zipcodeSearchText: string;
  // public NetOperatingIncomeMin : number;
  // public NetOperatingIncomeMax : number;
  // public SaleTypeCondition : string;
  // public CapRateMin : number;
  // public CapRateMax : number;
  public SWLat:number;
  public SWLng:number;
  public NELat:number;
  public NELng:number;

  public PropertySizeMin: number;
  public PropertySizeMax: number;
  public PropertyGrade :string;
  public Tenancy : string;
  public LeasedSqMMin :number;
  public LeasedSqMMax :number;
  public SignDateMax :string;
  public SignDateMin:string;
  public SignDateMinFormat : NgbDateStruct;
  public SignDateMaxFormat : NgbDateStruct;
  public DateCreatedMax :string;
  public DateCreatedMin:string;
  public DateCreatedMinFormat : NgbDateStruct;
  public DateCreatedMaxFormat : NgbDateStruct;
  public SubleaseFilter:number;
  public LandLordRepCompany :string;
  public TenantRepCompany :string;
  public TenantName :string;
  public LandLordName :string;*/

  LeaseID : number =null;
  PropertyTypes:string = null;
  SpecificUseId:string = null;
  PropertyID: number = null;
  PropertyName: string = null;
  Address : string = null;
  CityIDs:string = null;
  ZipCodes:string = null;   
  CountryId: number =null; 
  PropertySizeMin :number = null;
  PropertySizeMax :number = null;
  PropertyGrades  :string = null;
  Tenancys :string =null;
  LeasedSFMin :number = null;
  LeasedSFMax :number = null;
  SignDateMin:any = null;
  SignDateMax:any = null;
  ExecutionDateMin:any = null;
  ExecutionDateMax:any = null;
  SubLeaseFilter :number = null;
  AskingRateMin:number = null;
  AskingRateMax:number = null;
  LandlordRepCompanys :string = null;
  TenantRepCompanys :string = null;
  TenantNames :string = null;
  LandlordNames :string = null;
  DateCreatedMin:any = null;
  DateCreatedMax:any = null;    
  PolygonText:string = null;
  Cur_Latitude:number = null;
  Cur_Longitude :number = null;    
  Radius:number = null;  
  citySearchText: string= null; 
  zipcodeSearchText: string= null; 
  LatlngArray: any = null;  
  ExpiryDateMin:any = null;
  ExpiryDateMax:any = null;
  DateOccupiedMin:any = null;
  DateOccupiedMax:any = null;
  public CircleRadius: number;
  public CentreLatitude: number;
  public CentreLongitude: number;
  public SWLat:number;
  public SWLng:number;
  public NELat:number;
  public NELng:number;
  public SignDateMinFormat : NgbDateStruct;
  public SignDateMaxFormat : NgbDateStruct;
  public DateCreatedMinFormat : NgbDateStruct;
  public DateCreatedMaxFormat : NgbDateStruct;
  public ExecutionDateMinFormat :NgbDateStruct;
  public ExecutionDateMaxFormat :NgbDateStruct;
  public ExpiryDateMinFormat : NgbDateStruct;
  public ExpiryDateMaxFormat : NgbDateStruct;
  public DateOccupiedMinFormat : NgbDateStruct;
  public DateOccupiedMaxFormat : NgbDateStruct;

  PageNo :number = null;
  PageSize:number = null;
  SortBy :string = null;
  SortDirection :string = null;
  SortParam : string = null;
  StartingIndex: number;
  OffsetValue: number;
}

