import { NumberSymbol } from "@angular/common/src/i18n/locale_data_api";
import {Broker} from './Broker'
export class Transaction{
    TransactionId:number;
    SignDate:string;
    BuyerName:string;
    BuyerAddress:string;
    BuyerPhone:number;
    SellerName:string;
    SellerAddress:string;
    SellerPhone:number;
    Tenant:string;
    SalePrice:string;
    SFSold:string;
    PricePerSF:string;
    Type:string;
    SFLeased:string;
    AskingRate:number;
    Term:number;
    Broker:string;
    ListPrice:string;
    SoldSQLFT:number;
    BldgPSQFT:number;
    LotPSQFT:number;
    SaleDate:string;
    OccupancyDate:string;
    ExpirationDate:string;
    SimpleLeaseFee:number;
    DeedFileNumber:number;
    LoanDocNumber:number;
    OccupancyPercentage:number;
    CapRate:number;
    OperatingCosts:number;
    LoanAmount:number;
    LoanType:string;
    ListingComments:string;
    TransactionComments:string;
    BuyerBrokers:Broker[];
    SellerBrokers:Broker[];
    TenantType:string;
    SuiteLeased:number;
    LeasedSF:string;
    Floor:number;
    LeaseRate:number;
    EffectiveRate:number;
    LeaseRateType:string;
    FreeRent:string;
    FullFloor:string;
    TIAllowance:number;
    LeaseType:string;
    LandLordName:string;
    LandLordAddress:string;
    LandLordPhone:number;
    LandLordEmail:string;
    LandlordBrokers:Broker[];
    TenantBrokers:Broker[];
    RecordedDate: string;
    ListDate: string;
    isSelected: boolean;
    SaleID:number;

}
